// Generates committed test vectors for SAMIZDAT core library.
// Run: npm run generate-vectors
// Output is written to src/test-vectors/vectors.json.
//
// These vectors are the reproducibility guarantee — any correct implementation
// of the SAMIZDAT hashing and chunking spec must produce identical values.

import { writeFileSync } from 'node:fs';
import { hashLeaf, hashNode, sha256Raw, toHex } from '../src/core/hash';
import { computeMerkleRoot } from '../src/core/merkle';
import { chunkData, hashFileContent, CHUNK_SIZE_MIN } from '../src/core/chunker';
import { buildManifest } from '../src/core/manifest';

async function main(): Promise<void> {
  const enc = new TextEncoder();

  // --- SHA-256 raw ---
  const raw_empty = toHex(await sha256Raw(new Uint8Array(0)));
  const raw_hello = toHex(await sha256Raw(enc.encode('hello')));
  const raw_hello_samizdat = toHex(await sha256Raw(enc.encode('hello samizdat')));

  // --- hashLeaf ---
  const leaf_empty = toHex(await hashLeaf(new Uint8Array(0)));
  const leaf_hello = toHex(await hashLeaf(enc.encode('hello')));
  const leaf_hello_samizdat = toHex(await hashLeaf(enc.encode('hello samizdat')));

  // --- hashNode ---
  const nodeLeft  = new Uint8Array(32).fill(0x01);
  const nodeRight = new Uint8Array(32).fill(0x02);
  const node_01_02 = toHex(await hashNode(nodeLeft, nodeRight));
  const node_02_01 = toHex(await hashNode(nodeRight, nodeLeft)); // order matters

  // --- Merkle roots ---
  // Inputs are 32-byte arrays filled with a constant (not real leaf hashes;
  // these test the tree structure independently of hashLeaf).
  const merkle_1  = toHex(await computeMerkleRoot([[0x01].map(() => new Uint8Array(32).fill(0x01))[0]!]));
  const leaves234 = [0x01, 0x02, 0x03, 0x04].map(b => new Uint8Array(32).fill(b));
  const merkle_2  = toHex(await computeMerkleRoot(leaves234.slice(0, 2)));
  const merkle_3  = toHex(await computeMerkleRoot(leaves234.slice(0, 3)));
  const merkle_4  = toHex(await computeMerkleRoot(leaves234));

  // --- Chunker ---
  const helloData = enc.encode('hello samizdat');
  const helloChunks = await chunkData(helloData, CHUNK_SIZE_MIN);

  // Fixed 3000-byte input (all 0x42) split at CHUNK_SIZE_MIN boundary.
  const fixed3k = new Uint8Array(3000).fill(0x42);
  const fixed3kChunks = await chunkData(fixed3k, CHUNK_SIZE_MIN);

  const fileHash_hello_samizdat = await hashFileContent(helloData);

  // --- Manifest ---
  const { manifest: simpleManifest } = await buildManifest(
    [{ filename: 'article.txt', contentType: 'text/plain', data: helloData }],
    { title: 'Test Article', chunkSize: CHUNK_SIZE_MIN },
  );

  const { manifest: multiFileManifest } = await buildManifest(
    [
      { filename: 'a.txt', contentType: 'text/plain', data: enc.encode('file a') },
      { filename: 'b.txt', contentType: 'text/plain', data: enc.encode('file b contents are longer') },
    ],
    { authorMode: 'pseudonymous', chunkSize: CHUNK_SIZE_MIN },
  );

  const vectors = {
    _comment: 'SAMIZDAT core test vectors — generated by scripts/generate-vectors.ts',
    _version: '1',
    sha256Raw: {
      empty: raw_empty,
      hello: raw_hello,
      hello_samizdat: raw_hello_samizdat,
    },
    hashLeaf: {
      empty: leaf_empty,
      hello: leaf_hello,
      hello_samizdat: leaf_hello_samizdat,
    },
    hashNode: {
      '0x01_32bytes_then_0x02_32bytes': node_01_02,
      '0x02_32bytes_then_0x01_32bytes': node_02_01,
    },
    merkleRoot: {
      one_leaf_0x01: merkle_1,
      two_leaves_0x01_0x02: merkle_2,
      three_leaves_0x01_0x02_0x03: merkle_3,
      four_leaves_0x01_0x02_0x03_0x04: merkle_4,
    },
    chunker: {
      hello_samizdat: {
        input_bytes: helloData.length,
        chunk_size: CHUNK_SIZE_MIN,
        chunk_count: helloChunks.length,
        chunks: helloChunks.map(c => ({ index: c.index, size: c.size, hash: c.hash })),
      },
      fixed_3000_x42: {
        input_bytes: 3000,
        chunk_size: CHUNK_SIZE_MIN,
        chunk_count: fixed3kChunks.length,
        chunks: fixed3kChunks.map(c => ({ index: c.index, size: c.size, hash: c.hash })),
      },
      file_hash_hello_samizdat: fileHash_hello_samizdat,
    },
    manifest: {
      simple: {
        file_count: simpleManifest.fileTree.length,
        chunk_count: simpleManifest.chunkTree.length,
        root_hash: simpleManifest.rootHash,
        file_hash: simpleManifest.fileTree[0]!.hash,
      },
      multi_file: {
        file_count: multiFileManifest.fileTree.length,
        chunk_count: multiFileManifest.chunkTree.length,
        root_hash: multiFileManifest.rootHash,
        file_hashes: multiFileManifest.fileTree.map(f => f.hash),
      },
    },
  };

  const outPath = new URL('../src/test-vectors/vectors.json', import.meta.url).pathname;
  writeFileSync(outPath, JSON.stringify(vectors, null, 2) + '\n');
  console.log(`Written: ${outPath}`);
}

main().catch(err => { console.error(err); process.exit(1); });
